#!/usr/bin/env zsh

source "$CONFIG_DIR/environment"
source "$THEME_DIR/catppuccin"
source "$THEME_DIR/aerospace"
source "$HELPERS_DIR/globals"
source "$HELPERS_DIR/helpers"
source "$HELPERS_DIR/front_app"

function create_app_item() {
  DISPLAY_ID=$1
  WORKSPACE_ID=$2
  APP_NAME=$3
  APP_ID=$4

  icon=$(get_app_icon $APP_NAME)
  icon_font="$(get_app_icon_font $APP_NAME)"

  if [[ "$(get_verbose_mode)" -eq "1" ]]; then
    visible="on"
    width="24"
  else
    visible="off"
    width="0"
  fi
 
  name=apps."$APP_ID"

  sketchybar --add item $name left \
             --subscribe $name aerospace_toggle_app_icons \
             --set $name \
                   display="$DISPLAY_ID" \
                   background.drawing=Off \
                   width="$width" \
                   icon.drawing=$visible \
                   icon=$icon \
                   icon.font="$icon_font" \
                   script="$PLUGIN_DIR/aerospace_apps"
  
  add_app_to_cache $APP_ID $WORKSPACE_ID
}

function create_app_bracket_for_workspace() {
  DISPLAY_ID=$1
  WORKSPACE_ID=$2
 
  IFS=$'\n' apps=( $(aerospace list-windows --workspace $WORKSPACE_ID | awk 'BEGIN {FS="|"} {gsub(/^[ \t]+|[ \t]+$/, "", $2); gsub(/^[ \t]+|[ \t]+$/, "", $1);$1=$1; print $1":"$2}' ) )
  
  app_count=${#apps[@]}
  
  if [[ "$app_count" -eq "0" ]]; then
    return 1  
  fi

  for app in ${apps[@]}; do
    app_id=$(echo $app | awk 'BEGIN {FS=":"} {print $1}')
    app_name=$(echo $app | awk 'BEGIN {FS=":"} {print $2}')
    create_app_item $DISPLAY_ID $WORKSPACE_ID $app_name $app_id
  done

}

function create_workspace_item() {
  DISPLAY_ID=$1
  WORKSPACE_ID=$2
  VISIBLE=$3

  init_workspace_cache $WORKSPACE_ID

  sketchybar --add item  workspace."$WORKSPACE_ID" left \
                          --subscribe workspace."$WORKSPACE_ID" aerospace_workspace_change \
                          --set       workspace."$WORKSPACE_ID" \
                                      display="$DISPLAY_ID" \
                                      background.drawing=off \
                                      background.padding_left="0" \
                                      background.padding_right="0" \
                                      click_script="aerospace workspace $WORKSPACE_ID" \
                                      icon=${(P)${:-WORKSPACE_ICON_$WORKSPACE_ID}} \
                                      icon.padding_right=$ICON_PADDING \
                                      icon.padding_left=$ICON_PADDING \
                                      icon.drawing=$VISIBLE \
                                      label.drawing=Off \
                                      script="$PLUGIN_DIR/aerospace $WORKSPACE_ID"

    create_app_bracket_for_workspace $DISPLAY_ID $WORKSPACE_ID
}

function create_workspace_bracket_for_monitor() {
  active_workspace=$(aerospace list-workspaces --focused)
  MONITOR_ID=${@[1]}
  MONITOR_WORKSPACES=${@:2}
  display_id=$(get_display_id "$MONITOR_ID")

  sketchybar --add item  bracket_workspaces_spacer_left_$MONITOR_ID left \
           --subscribe bracket_workspaces_spacer_left_$MONITOR_ID aerospace_verbose_mode_toggled \
           --subscribe bracket_workspaces_spacer_left_$MONITOR_ID aerospace_node_moved_to_workspace \
           --set       bracket_workspaces_spacer_left_$MONITOR_ID \
                       display="$display_id" \
                       width="8" \
                       background.drawing=off \
                       label.drawing=off \
                       script="$PLUGIN_DIR/aerospace"

 monitor_workspace_array=( ${=MONITOR_WORKSPACES} )

 for workspace_id in $monitor_workspace_array; do
    windows_count=$(aerospace list-windows --workspace $workspace_id --count)
    if [ $active_workspace -eq $workspace_id ] || [ $windows_count -gt 0 ] ; then
      create_workspace_item "$display_id" "$workspace_id" "on"
    else
      create_workspace_item "$display_id" "$workspace_id" "off"
    fi
  done

#  if [ $monitor_id -lt ${#monitor_ids[@]} ]; then
#    sketchybar --add item bracket_workspaces_monitor_separator."$monitor_id" left \
#               --set      bracket_workspaces_monitor_separator."$monitor_id" \
#                          background.drawing=off \
#                          label.padding_left="0" \
#                          label.padding_right="0" \
#                          label.font.size="$BACKGROUND_HEIGHT" \
#                          label="|"
#  else
    sketchybar --add item bracket_workspaces_spacer_right_$MONITOR_ID left \
               --set      bracket_workspaces_spacer_right_$MONITOR_ID \
                          display=$display_id \
                          width="8" \
                          background.drawing=off \
                          label.drawing=off
#  fi

  sketchybar --add bracket workspaces."$MONITOR_ID" "/bracket\.*/" \
             --set         workspaces."$MONITOR_ID" \
                           display="$display_id" \
                           background.padding_left="0" \
                           background.corner_radius="$BRACKET_BACKGROUND_CORNER_RADIUS" \
                           background.border_width="$BRACKET_BACKGROUND_BORDER_WIDTH"
}

function get_display_id() {
  MONITOR_ID=$1
  display_id=$(aerospace list-monitors --format "%{monitor-appkit-nsscreen-screens-id};%{monitor-id}" | awk -F ";" -v monid=$MONITOR_ID '{if ($1==monid) {print $2}}')
  echo $display_id
}

function get_monitor_id() {
  DISPLAY_ID=$1
  monitor_id=$(aerospace list-monitors --format "%{monitor-appkit-nsscreen-screens-id};%{monitor-id}" | awk -F ";" -v dispid=$DISPLAY_ID '{if ($2==dispid) {print $1}}')
  echo $monitor_id
}

function is_workspace_in_monitor() {
  WORKSPACE_ID=$1
  MONITOR_ID=$2

  workspaces_for_monitor_id=( $(aerospace list-workspaces --monitor $MONITOR_ID) )
#  echo $workspaces_for_monitor_id
  for workspace in ${workspaces_for_monitor_id[@]}; do
    # echo "$workspace"
    if [[ "$WORKSPACE_ID" -eq "$workspace" ]]; then
      echo 1
      return 1
    fi
  done
  echo 0
}

AEROSPACE_CACHE_DIR=$CACHE_DIR/aerospace
AEROSPACE_VERBOSE_FILE=$AEROSPACE_CACHE_DIR/verbose

function init_aerospace_cache() {
  echo "Creating $AEROSPACE_CACHE_DIR"
  mkdir -p $AEROSPACE_CACHE_DIR
}

function get_verbose_mode() {
  local verbose_mode=0
  
  if [ -f $AEROSPACE_VERBOSE_FILE ] ; then
    verbose_mode=$(cat $AEROSPACE_VERBOSE_FILE)
  fi

  echo $verbose_mode
}

function toggle_verbose_mode() {  
  if [ -f $AEROSPACE_VERBOSE_FILE ] ; then
    local verbose_mode=$(cat $AEROSPACE_VERBOSE_FILE)
    let "verbose_mode=(verbose_mode+1)%2"
  else
    local verbose_mode=0
  fi
  echo $verbose_mode > $AEROSPACE_VERBOSE_FILE
  echo $verbose_mode
}

function init_workspace_cache() {
  WORKSPACE_ID=$1
  filename="$AEROSPACE_CACHE_DIR/$WORKSPACE_ID"
  if [[ ! -a $filename ]]; then
   touch 
  fi
  truncate -s 0 $filename
}

function add_app_to_cache()
{
  APP_ID=$1
  WORKSPACE_ID=$2
  echo $APP_ID >> "$AEROSPACE_CACHE_DIR/$WORKSPACE_ID"
}

function reset_workspace_cache() {
  WORKSPACE_ID=$1
  
  init_workspace_cache $WORKSPACE_ID 
  
  IFS=$'\n' apps=( $(aerospace list-windows --workspace $WORKSPACE_ID | awk 'BEGIN {FS="|"} {gsub(/^[ \t]+|[ \t]+$/, "", $1); print $1}' ) )
  
  app_count=${#apps[@]}
  
  if [[ "$app_count" -eq "0" ]]; then
    return 1  
  fi

  for app in ${apps[@]}; do
    app_id=$(echo $app | awk 'BEGIN {FS=":"} {print $1}')
    add_app_to_cache $app_id $WORKSPACE_ID
  done

}

function get_app_ids() {
  WORKSPACE_ID=$1
  
  IFS=$'\n' apps=( $(aerospace list-windows --workspace $WORKSPACE_ID | awk 'BEGIN {FS="|"} {gsub(/^[ \t]+|[ \t]+$/, "", $1); print $1}' ) )

  for app_id in ${apps[@]} ; do
    echo $app_id
  done
}

function get_cached_app_ids() {
  WORKSPACE_ID=$1
  filename="$AEROSPACE_CACHE_DIR/$WORKSPACE_ID"
  cat $filename
}

function compare_to_cache() {
  WORKSPACE_ID=$1
  app_id=$(diff <(get_app_ids $WORKSPACE_ID | sort) <(get_cached_app_ids $WORKSPACE_ID | sort) | grep '>' | sed 's/^>\ //g')
  echo $app_id
}

function move_app_to_workspace() {
  APP_ID=$1
  FROM_WORKSPACE_ID=$2
  TO_WORKSPACE_ID=$3
  sketchybar --move apps.$APP_ID after workspace.$TO_WORKSPACE_ID
  reset_workspace_cache $TO_WORKSPACE_ID
  reset_workspace_cache $FROM_WORKSPACE_ID
  sketchybar --update
  
}

