#!/usr/bin/env zsh

source "$CONFIG_DIR/environment"
source "$THEME_DIR/catppuccin"

get_app_icon() {
  app_name=$1
  case $app_name in
    Terminal|kitty|iTerm2) 
      icon=
      ;;
    Calculator) 
      icon=
      ;;
    Safari) 
      icon=
      ;;
    LinkedIn) 
      icon=
      ;;
    Dock|Docker|"Docker Desktop") 
      icon=
      ;;
    YouTube) 
      icon=
      ;;
    "Google Chrome") 
      icon=
      ;;
    Messages) 
      icon=
      ;;
    "Adobe Photoshop 2025") 
      icon=
      ;;
    Netflix|"Sky Showtime") 
      icon=
      ;;
    "Prime Video")
      icon=
      ;;
    Finder)
      icon=
      ;;
    "Microsoft Outlook") 
      icon=
      ;;
    Reminders) 
      icon=
      ;;
    Notes) 
      icon=
      ;;
    Acrobat) 
      icon=
      ;;
    Code|Cursor) 
      icon=
      ;;
    Preview) 
      icon=
      ;;
    "Font Book") 
      icon=
      ;;
    "Microsoft Excel")
      icon=
      ;;
    "Microsoft Word")
      icon=
      ;;
    "Microsoft PowerPoint")
      icon=
      ;;
    Medium)
      icon=
      ;;
    *) 
      icon=
      ;;
  esac
  echo $icon
}

get_app_icon_font() {
  app_name=$1
  case $app_name in
    Finder|LinkedIn|Dock|Docker|"Docker Desktop"|YouTube|"Google Chrome"|"Prime Video"|Medium) 
      icon_font="$ICON_FONT_BRANDS"
      ;;
    *) 
      icon_font="$ICON_FONT"
      ;;
  esac
  echo $icon_font 
}
