#!/usr/bin/env zsh

source "$CONFIG_DIR/environment"
source "$THEME_DIR/catppuccin"

get_app_icon_2() {
  app_name=$1
#   icon=$(printf '\uf120')
  icon='\ue920'
  # print $icon
  echo $icon
}

get_app_icon() {
  app_name=$1
  case $app_name in
    "System Settings")
      icon='\uf013'
      ;;
    Terminal|iTerm2) 
      icon='\uf120'
      ;;
    kitty)
      icon='\ue909'
      ;;
    Calculator) 
      icon='\uf1ec'
      ;;
    Safari) 
      icon='\uf267'
      ;;
    LinkedIn) 
      icon='\uf08c'
      ;;
    Dock|Docker|"Docker Desktop") 
      icon='\uf395'
      ;;
    YouTube) 
      icon='\uf167'
      ;;
    "Google Chrome") 
      icon='\uf268'
      ;;
    Messages) 
      icon='\ue913'
      ;;
    "Adobe Photoshop 2025") 
      icon='\ue902'
      ;;
    "Adobe Illustrator 2025") 
      icon='\ue903'
      ;;
    Netflix)
      icon='\ue90b'
      ;;
    "Sky Showtime")
      icon='\ue90a'
      ;;
    "HBO Max") 
      icon='\ue90c'
      ;;
    "Prime Video")
      icon='\uf270'
      ;;
    TV)
      icon='\ue90d'
      ;;
    "O'Reilly")
      icon='\ue906'
      ;;
    Finder)
      icon='\ue900'
      ;;
    "Microsoft Outlook") 
      icon='\ue90e'
      ;;
    Reminders) 
      icon='\uf0ae'
      ;;
    Notes) 
      icon='\uf249'
      ;;
    TextEdit)
      icon='\uf044'
      ;;
    Acrobat) 
      icon='\ue904'
      ;;
    Code) 
      icon='\ue907'
      ;;
    Cursor) 
      icon='\ue912'
      ;;
    Xcode) 
      icon='\ue908'
      ;;
    Preview) 
      icon='\uf5f5'
      ;;
    "Font Book") 
      icon=
      ;;
    "Microsoft Excel")
      icon='\ue911'
      ;;
    "Microsoft Word")
      icon='\ue90f'
      ;;
    "Microsoft PowerPoint")
      icon='\ue910'
      ;;
    Medium)
      icon='\uf23a'
      ;;
    "ChatGPT")
      icon='\ue7cf'
      ;;
    "App Store")
      icon='\uf370'
      ;;
    Figma)
      icon='\uf799'
      ;;
    reMarkable)
      icon='\ue905'
      ;;
    FaceTime)
      icon='\ue901'
      ;;
    *) 
      icon='\uf40e'
      ;;
  esac
  echo $icon
}

get_app_icon_font() {
  app_name=$1
  case $app_name in
    Figma|"App Store"|Safari|LinkedIn|Dock|Docker|"Docker Desktop"|YouTube|"Google Chrome"|"Prime Video"|Medium|"ChatGPT") 
      icon_font="$ICON_FONT_BRANDS"
      ;;
    FaceTime|Messages|reMarkable|TV|Finder|kitty|"Sky Showtime"|Netflix|"HBO Max"|"O'Reilly"|"Adobe Photoshop 2025"|"Adobe Illustrator 2025"|Acrobat|"Microsoft Excel"|"Microsoft Word"|"Microsoft PowerPoint"|Xcode|Code|Cursor|"Microsoft Outlook")
      icon_font="$APPICON_FONT"
      ;;
    *) 
      icon_font="$ICON_FONT"
      ;;
  esac
  echo $icon_font 
}

get_app_icon_font2() {
  echo "$APPICON_FONT"
}

