#!/usr/bin/env zsh

source "$CONFIG_DIR/environment"
source "$HELPERS_DIR/globals"
 
build_spacer() {
  name=$1
  position=$2
  sketchybar --add item $name $position \
             --set      $name \
                        background.drawing=off
}
get_toggle_icon() {
  if [[ $1 = true ]]; then
    echo ""  
    # echo ""  
  else
    echo ""
    # echo ""
  fi
}
build_toggle() {
  name=$1
  position=$2
  border_color=$3
  checked=$4
  toggle_icon=$(get_toggle_icon $checked)
  sketchybar --add item $name $position \
             --set      $name \
                        background.drawing=off \
                        icon.color=$border_color \
                        icon.drawing=on \
                        icon=$toggle_icon 
}

build_toggle_bracket() {
  item_name=$1
  bracket_name="${item_name}_bracket"
  left_spacer_name="${item_name}_spacer_left"
  right_spacer_name="${item_name}_spacer_right"
  toggle_name="${item_name}_toggle"
  position=$2
  item_builder=${item_name}_item_builder
  border_color=$3
  initial_value=$4

  build_spacer $left_spacer_name $position
  $item_builder $item_name $position
  build_spacer $right_spacer_name $position
  build_toggle $toggle_name $position $border_color $initial_value
  sketchybar --add bracket $bracket_name $left_spacer_name $item_name $toggle_name $right_spacer_name \
             --set         $bracket_name \
                           background.border_color="$border_color" \
                           background.corner_radius="$BRACKET_BACKGROUND_CORNER_RADIUS" \
                           background.border_width="$BRACKET_BACKGROUND_BORDER_WIDTH"
}
build_bracket() {
  item_name=$1
  bracket_name="${item_name}_bracket"
  left_spacer_name="${item_name}_spacer_left"
  right_spacer_name="${item_name}_spacer_right"
  position=$2
  item_builder=${item_name}_item_builder
  border_color=$3

  build_spacer $left_spacer_name $position
  $item_builder $item_name $position
  build_spacer $right_spacer_name $position
  sketchybar --add bracket $bracket_name $left_spacer_name $item_name $right_spacer_name \
             --set         $bracket_name \
                           background.border_color="$border_color" \
                           background.corner_radius="$BRACKET_BACKGROUND_CORNER_RADIUS" \
                           background.border_width="$BRACKET_BACKGROUND_BORDER_WIDTH"
}

change_bracket_color() {
  item_name=$1
  bracket_name="${item_name}_bracket"
  border_color=$2

  sketchybar --set $bracket_name \
                   background.border_color="$border_color"
  
  sketchybar --set $item_name \
                   label.color="$border_color" \
                   icon.color="$border_color" 
}

init_cache() {
  mkdir -p $CACHE_DIR
  init_counter
}

init_counter() {
  echo 0 > $COUNTER_FILE
}

next_counter() {
  if [ -f $COUNTER_FILE ] ; then
    counter=$(cat $COUNTER_FILE)
    let counter++
  else
    counter=0
  fi
  echo $counter > $COUNTER_FILE
  echo $counter
}
