#!/usr/bin/env zsh

source "$CONFIG_DIR/environment"
source "$HELPERS_DIR/aerospace"

sketchybar --add event aerospace_workspace_change
sketchybar --add event aerospace_verbose_mode_toggled
sketchybar --add event aerospace_toggle_app_icons
sketchybar --add event aerospace_node_moved_to_workspace

init_aerospace_cache

monitor_ids=( $(aerospace list-monitors | awk '{print $1}') )
# TODO:
# - Update this view when moving workspaces to a different monitors.
for monitor_id in ${monitor_ids[@]}; do
  workspaces_for_monitor_id=( $(aerospace list-workspaces --monitor $monitor_id) )
  create_workspace_bracket_for_monitor $monitor_id "${workspaces_for_monitor_id[@]}" 
done
