#!/usr/bin/env zsh

source "$CONFIG_DIR/environment"
source "$THEME_DIR/catppuccin"
source "$THEME_DIR/aerospace"

if [ "$SENDER" = "aerospace_workspace_change" ]; then
  if [ "$1" = "$FOCUSED_WORKSPACE" ]; then
    sketchybar --set $NAME \
                     icon.drawing=on \
                     icon="${(P)${:-ACTIVE_WORKSPACE_ICON_$1}}" \
                     icon.font="$ACTIVE_WORKSPACE_ICON_FONT"
  else
    windows_count=$(aerospace list-windows --workspace $1 --count)
    if [ $windows_count -eq 0 ] ; then
      VISIBLE="off"
    else
      VISIBLE="on"
    fi
    sketchybar --set $NAME \
                     icon.drawing=$VISIBLE \
                     icon="${(P)${:-WORKSPACE_ICON_$1}}" \
                     icon.font="$WORKSPACE_ICON_FONT"
  fi
  sketchybar --update
fi


