#!/usr/bin/env zsh

source "$CONFIG_DIR/environment"
source "$THEME_DIR/catppuccin"
source "$THEME_DIR/aerospace"
source "$HELPERS_DIR/aerospace"

echo "Here I am 2"

if [ "$SENDER" = "aerospace_toggle_app_icons" ]; then
  echo "Here I am"
  if [[ "$(get_verbose_mode)" -eq "1" ]]; then
    visible="on"
  else
    visible="off"
  fi
  sketchybar --set $NAME \
                   icon.drawing=$visible
  sketchybar --update
fi

