#!/usr/bin/env zsh

source "$CONFIG_DIR/environment"
source "$THEME_DIR/catppuccin"
source "$THEME_DIR/aerospace"
source "$HELPERS_DIR/aerospace"

if [ "$SENDER" = "aerospace_toggle_app_icons" ]; then
  if [[ "$(get_verbose_mode)" -eq "1" ]]; then
    visible="on"
    width="$ICON_WIDTH"
  else
    visible="off"
    width="0"
  fi
  sketchybar --set $NAME \
                   width="$width" \
                   icon.drawing=$visible
  sketchybar --update
fi

