#!/usr/bin/env zsh

source "$CONFIG_DIR/environment"
source "$HELPERS_DIR/front_app"

# Some events send additional information specific to the event in the $INFO
# variable. E.g. the front_app_switched event sends the name of the newly
# focused application in the $INFO variable:
# https://felixkratz.github.io/SketchyBar/config/events#events-and-scripting
if [ "$SENDER" = "front_app_switched" ] && [ ! -z "$INFO" ]; then
  icon_font="$(get_app_icon_font $INFO)"
  icon=$(get_app_icon $INFO)
  sketchybar --set "$NAME" \
                   label="$INFO" \
                   icon=$icon \
                   icon.font="$icon_font"
fi
