#!/usr/bin/env zsh

source "$CONFIG_DIR/environment"
source "$HELPERS_DIR/helpers"
source "$THEME_DIR/volume"

if [ "$SENDER" = "volume_change" ]; then
  VOLUME=$INFO
  
  case $VOLUME in
    [8-9][0-9]|100)
      ICON=$VOLUME_ICON_HIGH
      volume_color=$VOLUME_COLOR_HIGH
    ;;
    [4-7][0-9])
      ICON=$VOLUME_ICON_NORMAL
      volume_color=$VOLUME_COLOR_NORMAL
    ;;
    [1-9]|[1-3][0-9])
      ICON=$VOLUME_ICON_LOW
      volume_color=$VOLUME_COLOR_LOW
    ;;
    *) 
      ICON=$VOLUME_ICON_OFF
      volume_color=$VOLUME_COLOR_OFF
  esac

  sketchybar --set $NAME icon="$ICON" label="$VOLUME%" 
  change_bracket_color $NAME $volume_color
fi
